apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc
spec:
  replicas: 2
  selector:
    app: nginx
  template:
   metadata:
     labels:
       apps: nginx
       ver: 1.0

  spec:
    containers:
    - name: simple-pod
      image: nginx
      ports:
      - containerPort: 80
  
